# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yishan < Formula
  desc "CLI and local daemon for Yishan"
  homepage "https://github.com/yishan-io/yishan-mono"
  version "0.15.3"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yishan-io/yishan-mono/releases/download/v0.15.3/yishan-cli_0.15.3_darwin_amd64.tar.gz"
      sha256 "5376d824e25a4c23eceb8461d22bba0dd199f7338099584addf6ebb6a7f3fe6d"

      define_method(:install) do
        bin.install "yishan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yishan-io/yishan-mono/releases/download/v0.15.3/yishan-cli_0.15.3_darwin_arm64.tar.gz"
      sha256 "56375d0f491a634d9f7569a4fedc8f7d20e63597ff9a866339c72c6ea3ae5336"

      define_method(:install) do
        bin.install "yishan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yishan-io/yishan-mono/releases/download/v0.15.3/yishan-cli_0.15.3_linux_amd64.tar.gz"
      sha256 "bb71e4045955315d6b3c96458064dee13b7ede43480d44ec8e771d0a975bcf2a"
      define_method(:install) do
        bin.install "yishan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yishan-io/yishan-mono/releases/download/v0.15.3/yishan-cli_0.15.3_linux_arm64.tar.gz"
      sha256 "d8e14c240882284ed6660ff4c59cfe5b8c5dd67668dc2772dd2bdb4d044c9fe7"
      define_method(:install) do
        bin.install "yishan"
      end
    end
  end
end
