# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yishan < Formula
  desc "CLI and local daemon for Yishan"
  homepage "https://github.com/yishan-io/yishan-mono"
  version "0.15.0"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yishan-io/yishan-mono/releases/download/v0.15.0/yishan-cli_0.15.0_darwin_amd64.tar.gz"
      sha256 "2c20b735d4da267f8e72e90baba4fc130cfff5475748d56831ed947ff0015f95"

      define_method(:install) do
        bin.install "yishan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yishan-io/yishan-mono/releases/download/v0.15.0/yishan-cli_0.15.0_darwin_arm64.tar.gz"
      sha256 "5000c1f91cf48aa541c784b4df11322c183576405387904755b5501b4ccfcdf4"

      define_method(:install) do
        bin.install "yishan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yishan-io/yishan-mono/releases/download/v0.15.0/yishan-cli_0.15.0_linux_amd64.tar.gz"
      sha256 "fdc6c9d68b77b0ef6c602dbc73f58ec317eff4b125998b0b46342c6fdce64852"
      define_method(:install) do
        bin.install "yishan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yishan-io/yishan-mono/releases/download/v0.15.0/yishan-cli_0.15.0_linux_arm64.tar.gz"
      sha256 "a0bd3b9ccb5abd32e6f4ca3098c442431d906e74688feb98cf6cb860a5d4f32a"
      define_method(:install) do
        bin.install "yishan"
      end
    end
  end
end
