# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yishan < Formula
  desc "CLI and local daemon for Yishan"
  homepage "https://github.com/yishan-io/yishan-mono"
  version "0.15.0"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yishan-io/yishan-mono/releases/download/v0.15.0/yishan-cli_0.15.0_darwin_amd64.tar.gz"
      sha256 "dc5fb9a4ae968772a8e05a937e064dd5f926c08f25ebe796d6316f42d41bc5de"

      define_method(:install) do
        bin.install "yishan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yishan-io/yishan-mono/releases/download/v0.15.0/yishan-cli_0.15.0_darwin_arm64.tar.gz"
      sha256 "1bf161025c1d7a84b323bcc86a6b635b22326c3e76f4a725eacc9f03088ce415"

      define_method(:install) do
        bin.install "yishan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yishan-io/yishan-mono/releases/download/v0.15.0/yishan-cli_0.15.0_linux_amd64.tar.gz"
      sha256 "2da7242ce3f8748c3aede02bff7775275cec251bd150e13a82a2752bf406d3f9"
      define_method(:install) do
        bin.install "yishan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yishan-io/yishan-mono/releases/download/v0.15.0/yishan-cli_0.15.0_linux_arm64.tar.gz"
      sha256 "3e6eff8c6f281a8045b143a9bd4e7b727c8c6e4fb39d97e3f2065c2a116be851"
      define_method(:install) do
        bin.install "yishan"
      end
    end
  end
end
